# Generated by Django 5.1.4 on 2024-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('kg', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BMI',
                'db_table': 'BMI',
            },
        ),
    ]
